#!/usr/bin/python3
import random
import sys

def read_stdin():
    stdin_lines = []
    for stdin_line in sys.stdin:
        stdin_lines.append(stdin_line)
    return "".join(stdin_lines)

def read_args():
    argument = sys.argv[1:]
    return ' '.join(argument)

def get_message():
    args = read_args()
    if args:
        return args
    stdin = read_stdin()
    if stdin:
        return stdin

    return ''

if __name__ == "__main__":
    lines = open('/etc/mannaggia.d/mannaggia.dat').read().splitlines()
    saint = random.choice(lines)
    message = get_message()
    curse = "Mannaggia {}! {}".format(saint, message)
    print(curse)